spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    generate-ddl: true #spring.jpa.hibernate.ddl-auto ??? ???? ??, default = false
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true #hibernate? db? ??? ??? ????.
    properties:
      hibernate:
        format_sql: true #??? ???? ????.

jwt:
  secret-key: ${JWT_SECRET_KEY:asdf}
  access-exp: ${JWT_ACCESS_EXP:123456}