spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:mysql://3.35.128.136:3306/secretdiarydb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    generate-ddl: true #spring.jpa.hibernate.ddl-auto ??? ???? ??, default = false
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true #hibernate? db? ??? ??? ????.
    properties:
      hibernate:
        format_sql: true #??? ???? ????.
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

jwt:
  secret-key: ${JWT_SECRET_KEY:asdf}
  access-exp: ${JWT_ACCESS_EXP:123456}

server:
  port: 80